# Generated by Django 5.1.1 on 2024-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='Suffix')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('age', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationality')),
                ('ethnicity', models.CharField(blank=True, max_length=100, verbose_name='Ethnicity')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (cm)')),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('blood_type', models.CharField(blank=True, max_length=3, verbose_name='Blood Type')),
                ('natural_eye_color', models.CharField(blank=True, max_length=50, verbose_name='Natural Eye Color')),
                ('natural_hair_color', models.CharField(blank=True, max_length=50, verbose_name='Natural Hair Color')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('asthma', models.BooleanField(default=False, verbose_name='Do you have asthma?')),
                ('college_university', models.CharField(blank=True, max_length=200, verbose_name='College/University')),
                ('course', models.CharField(blank=True, max_length=200, verbose_name='Course')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Occupation')),
                ('hobbies_talents', models.TextField(blank=True, verbose_name='Hobbies and Talents')),
                ('smoke', models.BooleanField(default=False, verbose_name='Do you smoke?')),
                ('alcohol', models.BooleanField(default=False, verbose_name='Do you drink alcohol?')),
                ('first_day_last_cycle', models.DateField(blank=True, null=True, verbose_name='First Day of Last Menstrual Cycle')),
                ('menstrual_cycle_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Irregular', 'Irregular')], max_length=50, verbose_name='Type of Menstrual Cycle')),
                ('number_of_children', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Children')),
                ('hospitalization_reason', models.TextField(blank=True, verbose_name='If you have been hospitalized before, please state the reason/s.')),
                ('previous_egg_donor', models.BooleanField(default=False, verbose_name='Do you have previous experience being an Egg Donor?')),
                ('egg_donation_details', models.TextField(blank=True, verbose_name='If Yes, please list dates of egg donation and number of eggs retrieved')),
                ('reasons_for_donation', models.TextField(blank=True, verbose_name='What are your reasons for being an Egg Donor?')),
                ('travel_experience', models.BooleanField(default=False, verbose_name='Do you have international travel experience?')),
                ('travel_details', models.TextField(blank=True, verbose_name='Please list down countries and dates of travel')),
                ('willing_to_travel', models.BooleanField(default=False, verbose_name='Are you willing to travel abroad for the duration of your Egg Donation?')),
                ('current_location', models.CharField(blank=True, max_length=200, verbose_name='Current Location')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('share_contact_details', models.BooleanField(default=False, verbose_name='Are you comfortable in sharing your contact details with Intended Parents?')),
                ('post_donation_contact', models.BooleanField(default=False, verbose_name='Are you comfortable in keeping contact after donation?')),
                ('status', models.CharField(choices=[('For Approval', 'For Approval'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Not Approved', 'Not Approved'), ('Follow Up', 'Follow Up')], max_length=50, verbose_name='Status')),
                ('category', models.CharField(choices=[('New', 'New'), ('Proven', 'Proven')], max_length=50, verbose_name='Category')),
                ('facebook_name', models.CharField(blank=True, max_length=100, verbose_name='Facebook Name')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
            },
        ),
    ]
